### PR TITLE
resized version of the image

### PR DESCRIPTION
**Pull request by damac23**
Uses a real resized version of the image to display to save bandwidth especially if the uploaded images are pretty big.

### CODE REVIEW

**Comment by jayelkaake** [comment]
My issue with this PR is that reloading a product on every row of the grid is going to slow things down real bad. Can you think of a better solution?

Sorry for the super-late response!

**Comment by damac23** [comment]
Hmm.
Yes, maybe I can tweek this a little. I'll get back to you.

**Comment by jayelkaake** [comment]
Thanks!!!

**Comment by damac23** [comment]
I'm sorry, but some projects keep me too busy ... I've not forgotten it though

**Comment by jayelkaake** [comment]
I know that feels Klaus!

**Comment by jayelkaake** [comment]
Actually a simple solution to this is to go back to the config for enhancedgrid and Select the "thumbnail" image as a column instead. That image is already resized by Magento.

**Comment by damac23** [comment]
That doesn't work for the site I'm currently working on.

**Comment by damac23** [comment]
I'm working on the different approach and going to open another pull request.

**Comment by damac23** [comment]
Hi,

running with Magento 1.9.2.2 and your latest version from the repository:

* If I do not select "Thumbnails" it won't display any image even if "Show Image By Default" is set to "yes" - no problem, but you've mentioned that this might fix the problem with those large images.

* We do have cached images with the attributeName "thumbnail", but in the return of the collection there is always the reference to the original file. I don't see how I can change that.

After some thinking I don't see how I can make this happen any different than in this way, because I cannot safely recreate the MD5-portion of the cached path. Simply the fact that I might use a different size-setting for "thumbnail" in the backend than in the frontend.
Check this http://magento.stackexchange.com/questions/1005/get-original-image-file-from-a-cache-url for some insight to the cache-path.


So to match it with the dynamic columns, it would be something like this:
<pre>$out .= 'helper('catalog/image')->init(Mage::getModel('catalog/product')->load($row->getId()), $this->getColumn()->getIndex())->resize(self::$width, self::$height)." width='".self::$width."' ";</pre>

And even if this costs a lot, it's cheaper than loading >1MB images :)

cu
Klaus

**Comment by jayelkaake** [comment]
Have you tried changing the column in the config to "small_image"? Does that do the same thing?

**Pull request closed without merging**
